###
POST http://localhost:8080/api/invoice
Content-Type: application/json

{
  "totalCost": 22
}

###


###
GET http://localhost:8080/api/invoice/1

###


###
GET http://localhost:8080/api/invoice

###


###
PUT http://localhost:8080/api/invoice/1
Content-Type: application/json

{

  "totalCost": 33

}

###



###
DELETE  http://localhost:8080/api/invoice/1



###
