@startuml
left to right direction
class Customer {
    - name: String
    - designInvoices: DesignInvoice[]
    - invoices: Invoice[]
}

class Gardener {
    name :String
    tasks GardenerTask[]

}
class Product {

 - type :ProductType
 - price :double
 - amount :int
 - invoice: Invoice
 - durationOfTheInstallation: LocalDate
 - installationTasks: GardenerTask[]

}


enum ProductType {
    PLANT
    TOOL
    DECORATION
    GARDENDESIGN
}

class GardenerTask {
    - gardener: Gardener
    - product: Product
    - invoice: Invoice
    - salary: double
}
class Invoice  {
    - customer: Customer
    - products: Product[]
    - purchasedAmountOfProducts: int
    - tasksPerGardner: GardenerTask[]
    - totalPrice: double

}

Product "1" -- "*" GardenerTask
Invoice "1" -- "*" GardenerTask
Gardener "1" -- "*" GardenerTask
Customer "1" -- "*" Invoice
Product "*" -- "1" Invoice

@enduml
