@startuml

class Customer {
    - name: String
    - designInvoices: DesignInvoice[]
    - productInvoices: ProductInvoice[]
}
class GardenDesign {

  - name: String
  - type : String
  - extras: Product[]
  - buildingTasks: GardnerTask[]
  - invoices: DesignInvoice[]


}
class Gardner {
    name :String
    tasks GardnerTask[]

}
class Product {

 - type :ProductType
 - price :double
 - amount :int
 - invoices: ProductInvoice[]

}


enum ProductType {
    PLANT
    TOOL
    DECORATION
}

class GardnerTask {
    - gardner: Gardner
    - design: GardenDesign
}
class ProductInvoice  {
    - customer: Customer
    - products: Product
    - purchasedProductsAmount: int
    - price: double
}
class DesignInvoice {
    - customer: Customer
    - design: GardenDesign
    - price: double
    - amount: int

}

Customer "1" -- "*"  DesignInvoice
GardenDesign "1" -- "*" DesignInvoice
Gardner "1" -- "*" GardnerTask
GardenDesign "1" -- "*" GardnerTask
Customer "1" -- "*" ProductInvoice
Product "1" -- "*" ProductInvoice
GardenDesign "1" -- "0..*" Product

@enduml